# Generated by Django 5.0.6 on 2024-06-25 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_number', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('moto', models.TextField(blank=True, null=True)),
                ('school_type', models.CharField(choices=[('public', 'Public School'), ('private', 'Private School'), ('community', 'Community School')], default='public', max_length=20)),
                ('lga', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('school_email', models.EmailField(max_length=255)),
                ('school_phone_number', models.CharField(max_length=15)),
                ('school_website', models.URLField(blank=True, max_length=255, null=True)),
                ('program', models.CharField(choices=[('primary', 'Primary'), ('jss', 'Junior Secondary School'), ('all', 'All Programs')], default='all', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools_logo/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('program', models.CharField(choices=[('0', 'All Programs'), ('1', 'Primary'), ('2', 'Junior Secondary School')], default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(choices=[('1', 'First Term'), ('2', 'Second Term'), ('3', 'Third Term')], default='1', max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='schools.academicsession')),
            ],
        ),
    ]
