# Generated by Django 5.0.6 on 2024-10-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_number', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('motto', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('school_type', models.CharField(choices=[('public', 'Public School'), ('private', 'Private School'), ('community', 'Community School')], default='public', max_length=20)),
                ('program', models.CharField(choices=[('primary', 'Primary'), ('jss', 'Junior Secondary School'), ('sss', 'Senior Secondary School'), ('primary+jss', 'Primary + Junior Secondary School'), ('jss+sss', 'Junior Secondary School + Senior Secondary School'), ('all', 'All Programs')], default='all', max_length=12)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools_logo/%Y/%m/%d/')),
                ('registration_number', models.CharField(default='', max_length=50, unique=True)),
                ('accreditation_number', models.CharField(default='Not Available', max_length=50, unique=True)),
                ('lga', models.CharField(default='', max_length=50)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('ward', models.CharField(default='', max_length=50)),
                ('street_address', models.TextField(default='')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(choices=[('all', 'All schools'), ('public', 'Public schools'), ('private', 'Private schools'), ('community', 'Community schools'), ('individual', 'Individual schools')], default='all', max_length=10)),
                ('program', models.CharField(choices=[('primary', 'Primary Schools'), ('jss', 'Junior Secondary Schools'), ('sss', 'Senior Secondary Schools'), ('primary+jss', 'Primary + Junior Secondary Schools'), ('jss+sss', 'Junior Secondary Schools + Senior Secondary Schools'), ('all', 'All Programs')], default='all', max_length=12)),
                ('session_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='schools.school')),
            ],
            options={
                'unique_together': {('school', 'session_name')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('program', models.CharField(choices=[('primary', 'Primary'), ('jss', 'Junior Secondary School'), ('sss', 'Senior Secondary School')], default='primary', max_length=12)),
                ('is_general', models.BooleanField(default=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_1', models.DateField(blank=True, null=True)),
                ('end_date_1', models.DateField(blank=True, null=True)),
                ('start_date_2', models.DateField(blank=True, null=True)),
                ('end_date_2', models.DateField(blank=True, null=True)),
                ('start_date_3', models.DateField(blank=True, null=True)),
                ('end_date_3', models.DateField(blank=True, null=True)),
                ('academic_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='term_dates', to='schools.academicsession')),
            ],
        ),
    ]
