# Generated by Django 5.0.6 on 2024-12-15 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructureimage',
            name='infrastructure',
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_classrooms', models.PositiveSmallIntegerField(default=0)),
                ('classrooms_availability', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputerLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_computers', models.PositiveIntegerField(default=0)),
                ('internet_access', models.BooleanField(default=False)),
                ('smart_classrooms', models.BooleanField(default=False)),
                ('computer_lab_availability', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_type', models.CharField(choices=[('Physics Lab', 'Physics Lab'), ('Chemistry Lab', 'Chemistry Lab'), ('Biology Lab', 'Biology Lab'), ('Robotics Lab', 'Robotics Lab')], max_length=100)),
                ('lab_equipment', models.TextField(blank=True)),
                ('lab_availability', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_count', models.PositiveIntegerField(default=0)),
                ('digital_access', models.BooleanField(default=False)),
                ('study_space_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('library_availability', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('classroom', 'Classroom'), ('library', 'Library'), ('laboratory', 'Laboratory'), ('computer_lab', 'Computer Lab'), ('sports_facility', 'Sports Facility')], max_length=50)),
                ('image', models.ImageField(upload_to='infrastructure_images/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, help_text='Optional description of the image.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SportsFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('Football Field', 'Football Field'), ('Basketball Court', 'Basketball Court'), ('Volleyball Court', 'Volleyball Court'), ('Swimming Pool', 'Swimming Pool')], max_length=100)),
                ('field_availability', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Infrastructure',
        ),
        migrations.DeleteModel(
            name='InfrastructureImage',
        ),
    ]
