# Generated by Django 5.0.6 on 2024-12-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspensionclosure',
            name='is_statewide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateField(help_text='End date of the term.', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateField(help_text='Start date of the term.', null=True),
        ),
    ]
