# Generated by Django 5.0.6 on 2024-06-27 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='school_type',
            field=models.CharField(choices=[('all', 'All schools'), ('public', 'Public schools'), ('private', 'Private schools'), ('community', 'Community schools'), ('individual', 'Individual schools')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='session_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together={('school', 'session_name')},
        ),
    ]
