# Generated by Django 5.0.6 on 2024-10-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_number',
        ),
    ]
