# Generated by Django 5.0.6 on 2024-12-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_infrastructureimage_infrastructure_classrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolimages',
            name='description',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='images_description',
            field=models.TextField(blank=True, help_text='Optional description of the image.', null=True),
        ),
        migrations.AddField(
            model_name='computerlab',
            name='images_description',
            field=models.TextField(blank=True, help_text='Optional description of the image.', null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='images_description',
            field=models.TextField(blank=True, help_text='Optional description of the image.', null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='images_description',
            field=models.TextField(blank=True, help_text='Optional description of the image.', null=True),
        ),
        migrations.AddField(
            model_name='schoolimages',
            name='images_description',
            field=models.TextField(blank=True, help_text='Optional description of the image.', null=True),
        ),
        migrations.AddField(
            model_name='sportsfacility',
            name='images_description',
            field=models.TextField(blank=True, help_text='Optional description of the image.', null=True),
        ),
        migrations.AlterField(
            model_name='schoolimages',
            name='image_type',
            field=models.CharField(max_length=50),
        ),
    ]
