# Generated by Django 5.0.6 on 2024-11-01 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_school_school_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Principal', 'Principal'), ('Director', 'Director'), ('Liaison Officer', 'Liaison Officer'), ('Board Member', 'Board Member'), ('Trustee', 'Trustee')], max_length=50)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='schools.school')),
            ],
        ),
    ]
