# Generated by Django 5.0.6 on 2024-12-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_suspensionclosure_is_statewide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term_name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First Term'), (2, 'Second Term'), (3, 'Third Term')], help_text='Name of the term.', max_length=1),
        ),
    ]
