# Generated by Django 5.0.6 on 2024-06-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_academicsession_school_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_term', to='schools.school'),
        ),
        migrations.AddField(
            model_name='term',
            name='school_type',
            field=models.CharField(choices=[('all', 'All schools'), ('public', 'Public schools'), ('private', 'Private schools'), ('community', 'Community schools'), ('individual', 'Individual schools')], default='all', max_length=10),
        ),
    ]
