# Generated by Django 5.0.6 on 2024-12-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_schoolimages_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolimages',
            name='images_description',
        ),
    ]
