# Generated by Django 5.0.6 on 2024-12-23 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_term_term_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programlevel',
            name='school',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='vocational_department',
            field=models.ForeignKey(blank=True, help_text='The vocational department this subject belongs to, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.vocationaldepartment'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], default='upcoming', help_text='Current status of the academic session.', max_length=10),
        ),
        migrations.AlterField(
            model_name='levelclasses',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of students this class can accommodate.', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('core', 'Core'), ('religious', 'Religious'), ('vocational', 'Vocational'), ('local_language', 'Local Language')], default='core', help_text='Category of the subject.', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, help_text='Details about the subject.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_compulsory',
            field=models.BooleanField(default=True, help_text='Indicates whether this subject is compulsory for the associated program/level.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, help_text='The school this subject is specific to. Leave blank for general subjects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_subjects', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First Term'), (2, 'Second Term'), (3, 'Third Term')], help_text='Name of the term.'),
        ),
        migrations.CreateModel(
            name='ProgramLevelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('primary', 'Primary'), ('jss', 'Junior Secondary School'), ('sss', 'Senior Secondary School')], max_length=7)),
                ('level', models.CharField(help_text='Level name (e.g., Primary 1, JSS 2).', max_length=9)),
            ],
            options={
                'unique_together': {('program', 'level')},
            },
        ),
        migrations.AddField(
            model_name='levelclasses',
            name='program_level_template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='level_classes', to='schools.programleveltemplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='program_levels',
            field=models.ManyToManyField(blank=True, help_text='The levels this subject applies to (e.g., Primary 1, JSS 3).', related_name='subjects', to='schools.programleveltemplate'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='class_level',
            field=models.ForeignKey(help_text='The class level this fee applies to.', on_delete=django.db.models.deletion.CASCADE, to='schools.programleveltemplate'),
        ),
        migrations.AlterField(
            model_name='subjectgradingconfiguration',
            name='applicable_level',
            field=models.ForeignKey(help_text='The program level this grading configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='grading_configurations', to='schools.programleveltemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='levelclasses',
            unique_together={('program_level_template', 'class_section_name')},
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('science', 'Science'), ('arts', 'Arts'), ('commercial', 'Commercial')], max_length=10)),
                ('program_level_template', models.ForeignKey(help_text='The level this stream belongs to (e.g., SSS 1, JSS 2).', on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='schools.programleveltemplate')),
            ],
        ),
        migrations.AddField(
            model_name='levelclasses',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_sections', to='schools.stream'),
        ),
        migrations.AddField(
            model_name='subject',
            name='streams',
            field=models.ManyToManyField(blank=True, help_text='The streams this subject is specific to (e.g., Science, Arts).', related_name='subjects', to='schools.stream'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('subject_name', 'school', 'vocational_department'), name='unique_subject_within_school_and_department'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', True), ('vocational_department__isnull', True)), fields=('subject_name', 'category'), name='unique_general_subject_name_by_category'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='program',
        ),
        migrations.RemoveField(
            model_name='levelclasses',
            name='level',
        ),
        migrations.DeleteModel(
            name='ProgramLevel',
        ),
    ]
