# Generated by Django 5.0.6 on 2024-07-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_term_school_term_school_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('academic_session', 'term_name')},
        ),
        migrations.RemoveField(
            model_name='term',
            name='school',
        ),
        migrations.RemoveField(
            model_name='term',
            name='school_type',
        ),
    ]
