# Generated by Django 5.0.6 on 2024-11-22 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_stakeholder_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_of_instruction', models.CharField(choices=[('en', 'English'), ('hs', 'Hausa'), ('ff', 'Fulfulde'), ('yb', 'Yoruba'), ('ig', 'Igbo')], default=('en', 'English'), help_text='Primary language(s) used in teaching', max_length=2)),
                ('enrollment_capacity', models.PositiveSmallIntegerField(blank=True, help_text='Annual enrollment capacity of the school.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
