# Generated by Django 5.0.6 on 2024-11-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_schoolmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmetadata',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
