# Generated by Django 5.0.6 on 2024-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_subject_is_general_subject_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='program',
            field=models.CharField(choices=[('primary', 'Primary'), ('jss', 'Junior Secondary School'), ('sss', 'Senior Secondary School'), ('primary+jss', 'Primary + Junior Secondary School'), ('jss+sss', 'Junior Secondary School + Senior Secondary School'), ('all', 'All Programs')], default='all', max_length=12),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='session_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='program',
            field=models.CharField(choices=[('primary', 'Primary'), ('jss', 'Junior Secondary School'), ('sss', 'Senior Secondary School'), ('primary+jss', 'Primary + Junior Secondary School'), ('jss+sss', 'Junior Secondary School + Senior Secondary School'), ('all', 'All Programs')], default='all', max_length=12),
        ),
    ]
