# Generated by Django 5.0.6 on 2024-12-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_levelclasses_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='program',
            field=models.CharField(choices=[('primary', 'Primary'), ('jss', 'Junior Secondary School'), ('sss', 'Senior Secondary School'), ('primary+jss', 'Primary + Junior Secondary School'), ('jss+sss', 'Junior Secondary School + Senior Secondary School'), ('all', 'All Programs')], db_index=True, default='all', max_length=12),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_name'], name='idx_subject_name'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['category'], name='idx_category'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school'], name='idx_school'),
        ),
    ]
