# Generated by Django 5.0.6 on 2024-12-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_school_program_subject_idx_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='levelclasses',
            unique_together={('program_level_template', 'class_section_name', 'school')},
        ),
    ]
