# Generated by Django 5.0.6 on 2024-11-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_schoolmetadata_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='accreditation_number',
        ),
        migrations.CreateModel(
            name='AccreditationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_number', models.CharField(default='Not Available', max_length=15, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accreditated', 'Accreditated')], default=('pending', 'Pending'), max_length=12)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
