# Generated by Django 5.0.6 on 2024-07-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_academicsession_program_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='term',
            name='end_date_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='end_date_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='end_date_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='start_date_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='start_date_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='start_date_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='program',
            field=models.CharField(choices=[('primary', 'Primary Schools'), ('jss', 'Junior Secondary Schools'), ('sss', 'Senior Secondary Schools'), ('primary+jss', 'Primary + Junior Secondary Schools'), ('jss+sss', 'Junior Secondary Schools + Senior Secondary Schools'), ('all', 'All Programs')], default='all', max_length=12),
        ),
        migrations.AlterField(
            model_name='term',
            name='academic_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='term_dates', to='schools.academicsession'),
        ),
        migrations.RemoveField(
            model_name='term',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='term',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='term',
            name='term_name',
        ),
    ]
