# Generated by Django 5.0.6 on 2024-07-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_term_unique_together_term_end_date_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='program',
            field=models.CharField(choices=[('primary', 'Primary'), ('jss', 'Junior Secondary School'), ('sss', 'Senior Secondary School'), ('primary+jss', 'Primary + Junior Secondary School'), ('jss+sss', 'Junior Secondary School + Senior Secondary School'), ('all', 'All Programs')], default='primary', max_length=12),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=50),
        ),
    ]
