# Generated by Django 5.0.6 on 2024-12-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_levelclasses_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectgradingconfiguration',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectgradingconfiguration',
            name='applicable_level',
        ),
        migrations.RemoveField(
            model_name='subjectgradingconfiguration',
            name='grading_scale',
        ),
        migrations.RemoveField(
            model_name='subjectgradingconfiguration',
            name='school',
        ),
        migrations.RemoveField(
            model_name='subjectgradingconfiguration',
            name='weightage',
        ),
        migrations.CreateModel(
            name='SubjectRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('core', 'Core'), ('religious', 'Religious'), ('vocational', 'Vocational'), ('local_language', 'Local Language')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('program_levels', models.ManyToManyField(related_name='repository_subjects', to='schools.programleveltemplate')),
                ('streams', models.ManyToManyField(blank=True, related_name='repository_subjects', to='schools.stream')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_levels', models.ManyToManyField(related_name='school_subjects', to='schools.programleveltemplate')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_subjects', to='schools.school')),
                ('streams', models.ManyToManyField(blank=True, related_name='school_subjects', to='schools.stream')),
                ('subject_repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to='schools.subjectrepository')),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
