# Generated by Django 5.0.6 on 2024-11-23 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_remove_school_accreditation_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationstatus',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accreditationstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accreditated', 'Accreditated'), ('not-accreditated', 'Not Accreditated')], default=('pending', 'Pending'), max_length=16),
        ),
    ]
