# Generated by Django 5.0.6 on 2024-11-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_accreditationstatus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationstatus',
            name='accreditation_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accreditationstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accreditated', 'Accreditated'), ('not-accreditated', 'Not Accreditated'), ('cancelled', 'Accreditation cancelled')], default=('pending', 'Pending'), max_length=16),
        ),
    ]
