# Generated by Django 5.0.6 on 2024-12-26 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_remove_subjectgradingconfiguration_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolsubject',
            options={'verbose_name': 'School Subject', 'verbose_name_plural': 'School Subjects'},
        ),
        migrations.AlterUniqueTogether(
            name='schoolsubject',
            unique_together={('school', 'subject_repository')},
        ),
        migrations.AddField(
            model_name='schoolsubject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if this subject is currently active/offered by the school.'),
        ),
        migrations.AddField(
            model_name='schoolsubject',
            name='is_compulsory',
            field=models.BooleanField(default=True, help_text='Indicates if this subject is compulsory for students at the school.'),
        ),
        migrations.AlterField(
            model_name='schoolsubject',
            name='school',
            field=models.ForeignKey(help_text='The school offering this subject.', on_delete=django.db.models.deletion.CASCADE, related_name='offered_subjects', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='schoolsubject',
            name='subject_repository',
            field=models.ForeignKey(help_text='The subject from the central repository.', on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to='schools.subjectrepository'),
        ),
        migrations.RemoveField(
            model_name='schoolsubject',
            name='program_levels',
        ),
        migrations.RemoveField(
            model_name='schoolsubject',
            name='streams',
        ),
    ]
