# Generated by Django 5.0.6 on 2024-12-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_stream_schools_str_name_23a437_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentrepository',
            name='department',
            field=models.CharField(help_text='Name of the department', max_length=100),
        ),
        migrations.AlterField(
            model_name='departmentrepository',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
