# Generated by Django 5.0.6 on 2024-12-27 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_alter_departmentrepository_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrepository',
            name='vocational_department',
            field=models.ForeignKey(blank=True, help_text='Applicable only for vocational subjects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.departmentrepository'),
        ),
    ]
