# Generated by Django 5.0.6 on 2024-12-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0015_alter_gradeboundary_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialneedsresource",
            name="id",
        ),
        migrations.AlterField(
            model_name="specialneedsresource",
            name="school",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="schools.school",
            ),
        ),
    ]
