# Generated by Django 5.0.6 on 2024-12-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0017_alter_school_options_alter_school_is_vocational_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
