# Generated by Django 5.0.6 on 2024-12-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0018_alter_school_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="phone",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
    ]
